### ISSUE TITLE
Optimize Search Functionality

### ISSUE THREAD

**Issue by bchugg** [CodeTheChangeUBC/vjk#33]
Main page of site (access geared towards those without admin privileges), needs to be fully searchable. Might also require email functionality.

**Comment by bchugg** [comment]
@leesw98 Your search page is almost exactly what we need for this.

**Comment by bwdmonkey** [comment]
Then I guess I should work on this?

**Comment by angadkalra** [comment]
Try to remove any hardcoded stuff

**Comment by angadkalra** [comment]
Work on email first.

**Comment by ksenpi** [comment]
@angadkalra the search functionality (on the actual /search page) was implemented with javascript, mine was implemented in python, so because of the way these implementations interact with the front end, I don't think it's easy to swap one for the other. however, @leesw98's implementation looks really good, I don't think there's any reason why we need to swap it out. (+ the search implementation I wrote was somewhat customized for editing purposes, I used a lot of django formsets - in my opinion is somewhat unnecessary and clunky for just a regular search page!)

**Comment by angadkalra** [comment]
Okay sounds good. Thank you for investigating! I'll close this issue soon.
